image: maven:3.6.3-openjdk-15
include:
  - template: Code-Quality.gitlab-ci.yml
stages:
  - compile
  - test
  - coverage-jdk15
  - checkstyle

compile:
  stage: compile
  script:
    - cd despg
    - $MAVEN_HOME/bin/mvn clean compile

test-jdk15:
  stage: test
  script:
    - cd despg
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml

coverage-jdk15:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["test-jdk15"]
  dependencies:
    - test-jdk15
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml
  
checkstyle:
  stage: checkstyle
  script:
    - cd despg
    - $MAVEN_HOME/bin/mvn checkstyle:check
